version: '3'

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   image: agregert/fullcycle:desafio-docker-nginx
  #   container_name: nginx
  #   networks:
  #     - node-network
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - app

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: agregert/fullcycle:desafio-docker-node
    ports:
      - 8080:3000
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- /home/node/app/start.sh
    networks:
      - node-network
    volumes:
      - ./node/src:/home/node/app
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: agregert/fullcycle:desafio-docker-mysql
    command: --innodb-use-native-aio=0 
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
